### ISSUE TITLE
countries_trivia_game_script_load_questions_from_csv

### ISSUE THREAD

**Issue by propenster** [Py-Contributors/awesomeScripts#10]
## Script Title - countries_trivia.py

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by arnabsen1729** [comment]
I would like to work on this. Also, just to make sure I understood this properly, there will be a CSV file which will have the questions and the answers and the python script will load those questions and ask the those,  wait for user input, and will then give a remark if the answer was correct or wrong, and will continue this for all the questions. 

@propenster  can you please assign this issue to me. Also let me know if I understood it correctly.

**Comment by codeperfectplus** [comment]
@propenster Thanks for making the PR, But make sure to assigned on the issue before.

Have a good Day,

**Comment by propenster** [comment]
Hi, Deepak,
You should reassign me to something else will you?
Regards,
Faith - propenster

**Comment by codeperfectplus** [comment]
Hello, Propenster

I will create new issues for problem-solving scripts. Our main goal is to create scripts that can solve a problem.
I will create new issues soon. I am a little busy for Hackathon. you will see some cool problem-solving issues soon.

Keep an eye out.

**Comment by propenster** [comment]
Dear Deepak,
No problem... I can't wait... Thank you for making this opportunity
available for us...
Cheers,
Propenster.
