### ISSUE TITLE
Moving files automatically 

### ISSUE THREAD

**Issue by Neel2904** [Py-Contributors/awesomeScripts#101]
## Script Title -

**what will change** -  This python script will automatically move files from to source folder to desired folder.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Neel2904** [comment]
I would like to work on this.
**Assign me**

**Comment by mgadaphy** [comment]
I have already done something more advanced than this already. You can check it out at https://github.com/mgadaphy/Automatic-File-Arranger-in-Python

However, I can still work on this if you wish

**Comment by codeperfectplus** [comment]
I have also implemented File mover with CLI and GUI both.
feel free to check 
I did work on it a long time ago, feel free to improve
https://github.com/Py-Contributors/FileMoverGUI

**Comment by Neel2904** [comment]
Can I work on this issue?
