### ISSUE TITLE
Convert image to text

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/awesomeScripts#110]
## Script Title - Python script to fetch the text from an image and copy it to clipboard

**what will change** - I will add a script that lets you take a screenshot of the area on your screen, or a screenshot of an image on your screen and fetches the text from the image to the clipboard. This will be done with the help of pytesseract.

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by hot9cups** [comment]
I would like to be assigned to this issue

**Comment by joykirat18** [comment]
Can you please assign me this

**Comment by js899** [comment]
Can you assign me ? I've done this before

**Comment by codeperfectplus** [comment]
@joykirat18 @js899 
This issue is assigned to @hot9cups 
If you want to contribute to the code base. Please create a new issue.

- Report a Bug
- Add new Script
- Add new feature
