### ISSUE TITLE
convert image to pencil sketch

### ISSUE THREAD

**Issue by Neel2904** [Py-Contributors/awesomeScripts#112]
## Script Title -

**what will change** - This script will convert given image to pencil sketch using openCV

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SUKANTHEN** [comment]
Interested in this Task ! Can I Proceed

**Comment by Neel2904** [comment]
I had opened issue.
Can I work on this?

**Comment by codeperfectplus** [comment]
please use flake8 for linting python code.

**Comment by Neel2904** [comment]
sure!! Thanks
@codePerfectPlus 

> please use flake8 for linting python code.
