### ISSUE TITLE
Automating movies and TV series search using python scripts

### ISSUE THREAD

**Issue by harsh7x18** [Py-Contributors/awesomeScripts#117]
## Script Title - MINI-IMDB

**what will change** - IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@pyGitHub7 please make the necessary change in your to be merge.
Go through README.md and Contributing as well as for guidelines
