### ISSUE TITLE
Subtitle Creator

### ISSUE THREAD

**Issue by aaravm4** [Py-Contributors/awesomeScripts#127]
## Script Title - Subtitle Creator

**what will change** - There will be a new folder called `Subtitle Creator`, containing `subtitles.py` and a `readme.md` containing instructions on usage.

Code will basically make a new video file with subtitle text in it. 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code 

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aaravm4** [comment]
Can I work on this please?

**Comment by codeperfectplus** [comment]
can you please elaborate more on how it will create subtitle ?

**Comment by aaravm4** [comment]
For sure. Basically it can run speech recognition through the video with the `SpeechRecognition` module. Based on the timestamp of the text, it can then use `moviepy` to add text at the right times. @codePerfectPlus. I'm thinking of adding it as a small white Arial font at the bottom.

**Comment by eduardogpg** [comment]
Hello @ aaravm4, recently i was working in a similar project. I have Idea how moviepy working. For the transcribe we can use AWS translate. I don't know if it's allowed.

Thanks for you time.

**Comment by aaravm4** [comment]
Hi @eduardogpg I was thinking of using Wit.ai since it's free, since AWS Translate may be payed.

**Comment by codeperfectplus** [comment]
@aaravm4 It's a useful script. Go ahead

**Comment by aaravm4** [comment]
I'm still working on it
