### ISSUE TITLE
Automatic Folder Cleaner/Rearranger

### ISSUE THREAD

**Issue by chhipashubham970** [Py-Contributors/awesomeScripts#128]
I want to add a new python project in this repo.
The idea --Automatic Folder Cleaner/Rearranger

There are times when your downloads folder or any other directories have different types of files that you keep feeling too lazy to arrange them well into various folders like images, videos, audios, documents, compressed, programs, and folders for subfolders in that directory. 
This python script or script does such manual work for you with just one click.
This idea falls in a category named automate the boring stuff using python.
If you like the idea, please assign the task to me. I would contribute to this repo as part of Hacktoberfest.

**Comment by codeperfectplus** [comment]
For this check FileMover -  https://github.com/Py-Contributors/FileMoverGUI
