### ISSUE TITLE
Internshala Internships Scraper

### ISSUE THREAD

**Issue by TechTarun** [Py-Contributors/awesomeScripts#13]
## Internshala Scraper -

**what will change** -
* Will create a new script that will scrape internships of Internshala and make CSV out of it.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by TechTarun** [comment]
I have created this new issue and working on this script. Please assign it to me so that I can add it to this repo after 1st october.

**Comment by codeperfectplus** [comment]
- [x] Issue Assigned to @TechTarun

**Comment by TechTarun** [comment]
Thanks for assigning it to me. I will start contributing after 1st October.

**Comment by codeperfectplus** [comment]
ya sure
