### ISSUE TITLE
CoronaVirus Stats & Torrent Searcher Api

### ISSUE THREAD

**Issue by iamlordutkarsh** [Py-Contributors/awesomeScripts#130]
**Title** - Coronavirus Stats && Torrent Searcher Api

**what will change** - Program to get coronavirus stats Of any Country && Another Program To Get Magnet Links

**Assignees** -  @iamlordutkarsh 

### Type of Issue 
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Adding New Code

### Programming Language
- [x] Python

**Comment by codeperfectplus** [comment]
Create a separate folder for both the problem and use flake8 for code listing. 

Happy Coding

**Comment by iamlordutkarsh** [comment]
Can u label it for hacktoberfest

**Comment by codeperfectplus** [comment]
Pr don't need to be label as Hacktober. The label only is for encouraging people for Hacktober

**Comment by iamlordutkarsh** [comment]
As per New Update Hacktoberfest-accepted label should be used From 3rd October , Kindle add that label
