### ISSUE TITLE
Python face changer

### ISSUE THREAD

**Issue by Racherin** [Py-Contributors/awesomeScripts#131]
## Python face changer-

**Detect and change 2 or more face in an image ** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Muskan0510** [comment]
Hi, can I take this up?

**Comment by ashwinvin** [comment]
Hello, Please assign me this

**Comment by ashwinvin** [comment]
I completed the challenge. Please see #132

**Comment by aaravm4** [comment]
Be aware that your pull request can only be merged once you have been assigned an issue @ashwinvin .

**Comment by codeperfectplus** [comment]
@ashwinvin Issue is about detecting a face and change 2 or more face. don't create a PR without assigned.
