### ISSUE TITLE
Email sending script using smptlib: Making code robust

### ISSUE THREAD

**Issue by MNISAR** [Py-Contributors/awesomeScripts#133]
**Is your feature request related to a problem? Please describe.**
1. The code stops execution mid way when wrong input are given by the user.
2. I have to run code every time I want to sent another e-mail. 

**Describe the solution you'd like**
1. The code should explicitly do the check of input parameters and notify user if any input is invalid (regEx check)
2. Ask user at end if he/she wants to send another e-mail.

**Describe alternatives you've considered**
1. Use regular expression to verify the input given by the user.
2. Add a do-while loop to ask user each time to exit or send another e-mail.

**Additional context**

**Comment by codeperfectplus** [comment]
So do you want to improve it @MNISAR

**Comment by MNISAR** [comment]
Yes. @codePerfectPlus

**Comment by MNISAR** [comment]
@codePerfectPlus  I have added a pull request. Please check it.
