### ISSUE TITLE
Send telegram message

### ISSUE THREAD

**Issue by javim-h** [Py-Contributors/awesomeScripts#14]
## Script Title -Send telegram message to a user in Python
Add script to send telegram message using Python
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by javim-h** [comment]
I would like to contribute with this project

**Comment by codeperfectplus** [comment]
Please make sure to use the template to make an issue to better readability and understand. are you using python for that?
@YorozuyaDev

**Comment by javim-h** [comment]
Edited, im using Python yes

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @YorozuyaDev

**Comment by JulietaCaceres** [comment]
Can I contribute to this??

**Comment by codeperfectplus** [comment]
The issue already assigned to @YorozuyaDev
