### ISSUE TITLE
Speech to Text

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/awesomeScripts#148]
I would like to work on this issue.

## Script Title - This script will convert speech to text

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation

### Programming Language

- [✓] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
I would like to work on this issue

**Comment by codeperfectplus** [comment]
Please add module which works on windows and Linx as well or create 2 files for both os.
because some speech recognition tools specific to windows os

**Comment by shubham5351** [comment]
Ok I will add it.
