### ISSUE TITLE
Scrap the cricbuzz to get live updates.

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/awesomeScripts#149]
## Script Title - Scrap the cribuzz site to get all the live scores

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

- [✓] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Jaideep07** [comment]
I would like to work on this can you assign it to me.

**Comment by me-oniichan** [comment]
Seems like this work is not done yet, assign it tom me plz I would like to finish it.

**Comment by samin-batra** [comment]
@shubham5351 Can you assign to me if this is not being worked on?
