### ISSUE TITLE
YouTube feed video details scraper 

### ISSUE THREAD

**Issue by chawla201** [Py-Contributors/awesomeScripts#150]
## Script Title - YouTube feed video details scraper 

**what will change** -
A python script to scrape the title, views, link, upload date, likes, and dislikes for the first 500 videos in the order in which they are displayed on the youtube homepage and saving these details as a csv file.
This data can be used to analyze the viewing preferences and behavior of the user.
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by bachlis** [comment]
hello! I find this very interesting and would love to work on it.

**Comment by alyssapatricia** [comment]
Can you assign this to me? I'd be very hyped to work on it.

**Comment by codeperfectplus** [comment]
It's really a good script.
Happy Coding

**Comment by chawla201** [comment]
@codePerfectPlus I myself have a few ideas for this script and would like to work on it myself too. Can you please assign it to me as well?
