### ISSUE TITLE
Tool for Taking Screenshots

### ISSUE THREAD

**Issue by cozyxss** [Py-Contributors/awesomeScripts#158]
## Script Title - Python Screenshots

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by cozyxss** [comment]
I'll like to work with this ❤️

**Comment by codeperfectplus** [comment]
ya sure @bbetulkaya ,
Please can you explain a little bit about your code? How will it function?

**Comment by sendaljpt** [comment]
hi @bbetulkaya check this PR https://github.com/Py-Contributors/awesomeScripts/pull/160

**Comment by sendaljpt** [comment]
assign this issue to me

**Comment by cozyxss** [comment]
> ya sure @bbetulkaya ,
> Please can you explain a little bit about your code? How will it function?

I will use tkinter and pyautogui library in my code. I'll define take_shot() function with this library. When the code run user can screenshots in 3 sec.

I hope that has been revealing
