### ISSUE TITLE
Download songs from youtube | Python CLI.

### ISSUE THREAD

**Issue by Parasgupta44** [Py-Contributors/awesomeScripts#16]
##  Download mp3 file for the song entered by the user.

Download song by entering the name of song / artist on the terminal (converted to mp3).

### Instructions
- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions.
- add requirements.txt if needed.
- add your program name & Author name in the main readme.

Please add/delete options that are not relevant.
- [x] Adding new code.

### Programming Language.

- [x] Python

🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server - [https://discord.gg/FXyh2S3](https://discord.gg/FXyh2S3)

Happy Coding.

**Comment by Parasgupta44** [comment]
Hey...this is a very good repo in the long run. Would love to contribute!

**Comment by codeperfectplus** [comment]
@Parasgupta44 You are welcome to contribute, we are creating collections of the problem-solving python scripts.

Happy Coding
