### ISSUE TITLE
Genrerate random gradient images and saving as .png

### ISSUE THREAD

**Issue by dntandan** [Py-Contributors/awesomeScripts#162]
## Script Title - Gradient Images

**what will change** -
This script will generate and save random gradient patterns and will save them as .png extensions on completion using Pillow module.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ronanren** [comment]
can i assigned me to this task ?
