### ISSUE TITLE
text & image encryption

### ISSUE THREAD

**Issue by YaraYasser** [Py-Contributors/awesomeScripts#167]
## Script Title -

adding encryption for image and text

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by shrn2** [comment]
Please assign me to this task

**Comment by codeperfectplus** [comment]
@tre3x Issue is already assigned.
