### ISSUE TITLE
Make your Own Audio Books 

### ISSUE THREAD

**Issue by Keyurkariya** [Py-Contributors/awesomeScripts#174]
## Script Title - Audio Book Reader

**what will change** - Will add a new script which can read any audiobook based on the pdf provided can customize the speed and page number ranges.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/Hyasn97

Happy Hacktoberfest,

**Comment by codeperfectplus** [comment]
It's a helpful script. Thanks for your contribution to awesomeScripts.

**Comment by Keyurkariya** [comment]
> It's a helpful script. Thanks for your contribution to awesomeScripts.

Thanks, https://github.com/Py-Contributors/awesomeScripts/pull/176 here is the PR for the same.
