### ISSUE TITLE
Wallpaper Changer

### ISSUE THREAD

**Issue by SPOCTONE** [Py-Contributors/awesomeScripts#175]
## Wallpaper Changer

**Automate the process of changing your desktop wallpaper daily (with an element of randomness!) at a scheduled time of your choice.**

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
It's really a good script.

**Comment by SPOCTONE** [comment]
thanks! on my way to make a PR!
