### ISSUE TITLE
Move Files to Different Location according to extension

### ISSUE THREAD

**Issue by Araon** [Py-Contributors/awesomeScripts#185]
## Mover.py -

**Move Files to Different Location according to extension, Can be used in Download folder to unclutter it** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vighneshdeepweb** [comment]
can u assign me this issue @Araon

**Comment by Niharika-Arora** [comment]
I'd like to contribute to this issue @Araon

**Comment by codeperfectplus** [comment]
There is already a similar project to re-arrange download files in CLI and GUI mode. 
improvement are welcome- 
https://github.com/Py-Contributors/FileMoverGUI
