### ISSUE TITLE
Replace occurrences of a word in a file

### ISSUE THREAD

**Issue by nandacamargo** [Py-Contributors/awesomeScripts#187]
## Script Title - Replace occurrences of a word in a file by another word

**what will change** -
This new script will read a file and replace all occurrences of the first word with the second one.
How to use: python input_file.txt word1 word2

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by nandacamargo** [comment]
Hello, I would like to work on this issue.

**Comment by iriyagupta** [comment]
@nandacamargo Hi ! can i work on it?

**Comment by Kishore-abhimanyu** [comment]
I would also like to work on this. Can you please assign me on this?

**Comment by bhati-mukesh** [comment]
Hello, I would like to work on this. if possible can you please assign this to me also?

**Comment by nandacamargo** [comment]
Could you, please, review my PR? 
Add new script to replace words #226 
Thank you!
