### ISSUE TITLE
Python CLI script to check the weather of your city

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#19]
## Script Title - check the weather of your City using python CLI and openweathermap.org API

**Note**- Don't add your `API KEY` in the program, create env_variable to save KEY.

```bash
python check_weather <city_name>
```

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by roopeshvs** [comment]
Hello, I'd love to take this up.

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @roopeshvs 

Happy Coding
