### ISSUE TITLE
URL to QR code converter using Python

### ISSUE THREAD

**Issue by dhiganthrao** [Py-Contributors/awesomeScripts#190]
## QRCodeConverter 

**what will change** - Adding a simple script to convert URLs to QR Codes.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by dhiganthrao** [comment]
@codePerfectPlus if possible, please assign this issue to me so I can work on it for Hacktoberfest.

**Comment by dhiganthrao** [comment]
Thank you!

**Comment by dhiganthrao** [comment]
@codePerfectPlus whenever you have time, kindly review my pull request and merge if you see fit. Thank you once again!

**Comment by Kishan-Sahu** [comment]
can you assign it to me.
