### ISSUE TITLE
Sudoku Solver | Backtracking

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#20]
## Script Title - Sudoku Solver Script using Backtracking

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by BassCoder2808** [comment]
I would like to solve the given issue can you assign me this issue.

**Comment by codeperfectplus** [comment]
- [x] Issues assigning to @BassCoder2808 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by BassCoder2808** [comment]
Thanks!
