### ISSUE TITLE
Hill Cipher

### ISSUE THREAD

**Issue by jyothsnashaji** [Py-Contributors/awesomeScripts#200]
A  script to decrypt or decrypt a text using hill cipher.

**Comment by Kishore-abhimanyu** [comment]
I would like to work on this. Can you please assign me on this?

**Comment by Kishore-abhimanyu** [comment]
Can i also work on this? Could you assign me also for this work?

**Comment by Kishore-abhimanyu** [comment]
If this issue is for decryption then can i add the encryption script, already done the encryption script waiting to get assigned to me
