### ISSUE TITLE
Speed Test

### ISSUE THREAD

**Issue by mikek4233** [Py-Contributors/awesomeScripts#207]
## Script Title - Speed test

**what will change** -
Add a script that will run a speed test in the terminal
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by mikek4233** [comment]
Happy to work on this if assigned to me

**Comment by theanujdev** [comment]
May I do that?

**Comment by mikek4233** [comment]
I have actually already done it - just waiting to be assigned the issue so I can make a PR
