### ISSUE TITLE
Convert Ebook to Kindle Format | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#21]
## Script Title - Change format of File

```bash
python script.py <file_path>
```
**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by roopeshvs** [comment]
Hello, Can this be done with the instruction to install Calibre(https://calibre-ebook.com/download) and using its command-line function called with the help of a Python script to solve this?

**Comment by codeperfectplus** [comment]
You can solve it as you want.

there are some library is python too. if you want to check them

**Comment by roopeshvs** [comment]
Sure, then. Let me take this.
