### ISSUE TITLE
Add hill cipher encryption

### ISSUE THREAD

**Issue by Kishore-abhimanyu** [Py-Contributors/awesomeScripts#211]
Add script for hill cipher encryption

**Comment by Kishore-abhimanyu** [comment]
Could you please assign me on this?

**Comment by codeperfectplus** [comment]
#200 Duplicate issue

**Comment by Kishore-abhimanyu** [comment]
#200 is for decryption script

**Comment by codeperfectplus** [comment]
then please make your doubt clear with the issue creator on issue #200.
