### ISSUE TITLE
Downloads Folder Manager

### ISSUE THREAD

**Issue by eatmyaspirin** [Py-Contributors/awesomeScripts#213]
## Script Title - Downloads Folder Manager

**what will change** - This script will help segregate files in the downloads folder based on their type (extension) by creating new folders for the same.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by eatmyaspirin** [comment]
Please assign me to this, thanks!

**Comment by codeperfectplus** [comment]
this script already exists, feel free to improve https://github.com/Py-Contributors/FileMoverGUI
