### ISSUE TITLE
imdb-scraper

### ISSUE THREAD

**Issue by ben-jnr** [Py-Contributors/awesomeScripts#23]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ben-jnr** [comment]
Can I do this as part of hacktoberfest?

**Comment by codeperfectplus** [comment]
sure @ben-jnr

**Comment by ben-jnr** [comment]
> sure @ben-jnr

Thanks
