### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by brunobastos** [Py-Contributors/awesomeScripts#231]
## Currency Converter

Adds a new script to convert currencies.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by brunobastos** [comment]
I'd like to work on this one. Could you assign it to me? Thanks!

**Comment by SanyaNanda** [comment]
hey @brunobastos 
I would like to work on this, Please assign it to me

**Comment by SanyaNanda** [comment]
Hey can I work in it as well?
