### ISSUE TITLE
Port scanner

### ISSUE THREAD

**Issue by akamhy** [Py-Contributors/awesomeScripts#236]
## Script Title - port scanner

**what will change** - A fast* port scanner. 
fast = Threading and known common ports based

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by midhun1998** [comment]
Hey @akamhy . I would like to contribute to this issue. Can you assign it to me, please?

**Comment by akamhy** [comment]
> Hey @akamhy . I would like to contribute to this issue. Can you assign it to me, please?

I'm not the maintainer and I opened this issue to work on for the hacktoberfest event.
You can open your own issue to work on, any kind of useful script would work. 
And fyi @codePerfectPlus is the maintainer of this repo.

**Comment by midhun1998** [comment]
Cool. Thanks for the info @akamhy.

**Comment by akamhy** [comment]
Usage : 
```bash
python3 port_scanner.py <host-ip> --start <start-port> --end <end-port>
```

If optional args (--start and --end) are not supplied, default values are 0 and 65535(max case).
