### ISSUE TITLE
Get random fact

### ISSUE THREAD

**Issue by ghost** [Py-Contributors/awesomeScripts#239]
## Script Title -

**what will change** - This script can get a random fact. the type of fact can also be chosen, type can be one of the following: math, trivia, date, year, if not specified, a random fact type will be chosen.

It depends on NumberAPI, and the users don't even have to get their own api key.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by jp2373** [comment]
Can you assign this to me? I can do it
