### ISSUE TITLE
Text to Sound

### ISSUE THREAD

**Issue by cozyxss** [Py-Contributors/awesomeScripts#24]
## Script Title - Text to Sound

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by cozyxss** [comment]
can i work this on for hactoberfest?

**Comment by Taneesha-creates** [comment]
I'd love to take this up for hacktoberfest!

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @bbetulkaya ,
