### ISSUE TITLE
Flipkart.com Price Tracker

### ISSUE THREAD

**Issue by eatmyaspirin** [Py-Contributors/awesomeScripts#241]
## Script Title -

**what will change** - Track price changes for a particular product on flipkart.com and inform (via email) if the price drops below a set threshold.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by eatmyaspirin** [comment]
I would like to work on this

**Comment by codeperfectplus** [comment]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please leave a star(:star:) on other repo too.
Happy Coding
