### ISSUE TITLE
Error by calling send_telegram_message

### ISSUE THREAD

**Issue by ferhah** [Py-Contributors/awesomeScripts#246]
**Describe the bug**
If I try to send a telegram message via "send_telegram_message.py", I received the following error: 

send_telegram_message.py:22: RuntimeWarning: coroutine 'MessageMethods.send_message' was never awaited
  client.send_message(args.user, args.msg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**To Reproduce**
1. Install telethon via "pip install telethon"
2. Change api_id and api_hash inside send_telegram_message.py according to the instructions given in the same file
3. call python send_telegram_message.py <PHONE-NUMBER> <MESSAGE> 

**Enviroment:**
 - OS: Ubuntu 16.04
 - Python: 3.7.4

**Comment by ferhah** [comment]
I can try fixing the bug if you want.

**Comment by codeperfectplus** [comment]
Sure go ahead.
