### ISSUE TITLE
Youtube video downloader

### ISSUE THREAD

**Issue by eatmyaspirin** [Py-Contributors/awesomeScripts#250]
## Script Title - Youtube Video Downloader

**what will change** -
Script with GUI to download videos from youtube at 1080p (if available)
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by hemantsirsat** [comment]
i'll do it

**Comment by eatmyaspirin** [comment]
I would like to work on this

**Comment by GregCM** [comment]
I'm interested

**Comment by ish-u** [comment]
i would like to contribute

**Comment by ish-u** [comment]
is this issue closed ?

**Comment by eatmyaspirin** [comment]
> is this issue closed ?

will soon be

**Comment by ish-u** [comment]
Ok
