### ISSUE TITLE
amazon-price-alert Exceptions are not caught when price isn't found

### ISSUE THREAD

**Issue by habereet** [Py-Contributors/awesomeScripts#251]
**Describe the bug**
The script is supposed to monitor the price of an item on Amazon and send an email to a specified address when the price falls below a designated value.

The first time I used the script I got python exceptions that were uncaught.

I believe this is either because
-  the original developer wrote this for a different geographic location than I'm in and I'm seeing a different layout
_or_ 
- Amazon has changed the layout since it was written

**To Reproduce**
1. Install the required libraries
2. Run the script
2. Enter https://smile.amazon.com/Nintendo-Switch-Online-Family-Membership/dp/B07KY69YFM/ref=sxts_sxwds-bia-wc-drs1_0?cv_ct_cx=nintendo+switch&dchild=1&keywords=nintendo+switch&pd_rd_i=B07KY69YFM&pd_rd_r=927d6390-f518-4493-9549-3f44fc4bc277&pd_rd_w=xef68&pd_rd_wg=ZoNYD&pf_rd_p=ecbfa24d-f48c-4d5c-83aa-9549f4e7c925&pf_rd_r=ZBS2CH74FAP36HRWGREN&psc=1&qid=1602203672&sr=1-1-f6b8d51f-2c55-4dc3-89ad-0c3639671b2d as the url
3. Enter any price; I entered 20
4. Enter an email address
5. Enter a time period

**Expected behavior**
The script should run from this point. It should hit the url, find the price, and compare it against the budget.

**Screenshots**
I received the below exception
![image](https://user-images.githubusercontent.com/41403644/95528807-259a7500-09a7-11eb-9f7a-d1a6941a61bb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python: 3.8.6

**Comment by habereet** [comment]
Please assign to me

**Comment by codeperfectplus** [comment]
Thanks for finding bug. we are collecting problem-solving scripts but some of them are not tested.

**Comment by habereet** [comment]
Like I said, the original dev may have had a different layout but I'll add some try catch blocks.

**Comment by habereet** [comment]
Submitted a pull request #275 to resolve this
