### ISSUE TITLE
English Dictionary

### ISSUE THREAD

**Issue by alovictor** [Py-Contributors/awesomeScripts#252]
## English Dictionary

**what will change** - Add a new script thats gives the meaning of the input word.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by alovictor** [comment]
I would like to work on this!

**Comment by hisandeepangara** [comment]
assign to me

**Comment by GregCM** [comment]
I'm interested
