### ISSUE TITLE
Discord Bot with economy and level-up system

### ISSUE THREAD

**Issue by Vyvy-vi** [Py-Contributors/awesomeScripts#254]
## Script Title -
Tear_Drops
{a discord entertainment bot that has economy, levelup, wolfram query, etc...}
I would love to make this : )
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Vyvy-vi** [comment]
I would love to work on this

**Comment by Vyvy-vi** [comment]
Oh sorry I was a bit occupied with school
I will make a PR maybe tomorrow

**Comment by Vyvy-vi** [comment]
I have uploaded it
Just 1 or 2 commands left.
But, the bot is fully functional rn.
(Will add them after a week or 2)

**Comment by Vyvy-vi** [comment]
It was fun doing this project!
(except the linting part 😆  )

**Comment by codeperfectplus** [comment]
You bot looks cool. I will try it
