### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by jyothsnashaji** [Py-Contributors/awesomeScripts#264]
## Script Title -
Clock
**what will change** -
Script will include options to 
1. Display the current date and time, updated every millisecond (like a digital watch)
2. Start a timer for a given number of seconds/minutes
3. A stopwatch

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
hey, can you explain more about the script?

**Comment by jyothsnashaji** [comment]
It updates and displays the current time.

**Comment by jyothsnashaji** [comment]
It can be used to know the current time or as a timer or stopwatch
