### ISSUE TITLE
launch multiple ec2 instances

### ISSUE THREAD

**Issue by DiptoChakrabarty** [Py-Contributors/awesomeScripts#27]
## Script Title -
Launch multiple ec2 instances in aws using python

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by roopeshvs** [comment]
Hello, I'd like to take up this issue.

**Comment by HIMANSHU3107** [comment]
I'd like to work on this issue

**Comment by codeperfectplus** [comment]
@DiptoChakrabarty Please Lint your code according to Flake8 standards
