### ISSUE TITLE
Medium.com Article scrapper

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#272]
## Script Title - Scrap article from medium according to input the category in JSON format.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by HolgerDoerner** [comment]
Hello!
I would like to take this issue as part of Hacktoberfest 😄

**Comment by codeperfectplus** [comment]
Happy HacktoberFest
