### ISSUE TITLE
Merging 2 PDF's

### ISSUE THREAD

**Issue by AmeyaJain-25** [Py-Contributors/awesomeScripts#28]
## Script Title - Merging 2 PDF's
**what will change** -
It will merge two PDF's. I would be working on it
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ShahzaibJutt** [comment]
@AmeyaJain-25  Can you assign this to me?

**Comment by uditmore99** [comment]
I'd love to work on this !
Can you assign this to me ?
Happy to help here :)
