### ISSUE TITLE
Script to check ping to a gaming server

### ISSUE THREAD

**Issue by AbdulMAbdi** [Py-Contributors/awesomeScripts#285]
## PingTest -

**what will change** - A script that will check average ping over a period time to popular gaming servers 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AbdulMAbdi** [comment]
I would like to work on this, may it please be assigned to me.

**Comment by ivandzefen** [comment]
I would like to work on this
