### ISSUE TITLE
Validating password by taking input from user. 

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/awesomeScripts#29]
## Script Title - Validating Password

Validation Rules :
 At least 1 letter between [a-z] and 1 letter between [A-Z].
 At least 1 number between [0-9].
 At least 1 character from [$#@].
 Minimum length 6 characters.
 Maximum length 16 characters.

Input :
A3r@180a

Output :
Valid password

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Documentation

### Programming Language

- [✓] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
I would like to work on this issue.

**Comment by ShahzaibJutt** [comment]
I would love to work on this can you assign it to me?

**Comment by 0vj** [comment]
I would love to work on this can you assign it to me?

**Comment by srshobhit72** [comment]
Can you assign it to me?I would like to work on it.

**Comment by shrishtrip** [comment]
Can I work on this issue?
