### ISSUE TITLE
Image to ASCII art converter

### ISSUE THREAD

**Issue by pranshuj73** [Py-Contributors/awesomeScripts#291]
## Script Title - Image to ASCII art converter

**what will change** - Python script that takes in path to image as parameter and returns ascii art of that image

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by pranshuj73** [comment]
I'd like to work on this, please assign it to me.

**Comment by sohamsahare123** [comment]
I'd like to contribute to it

**Comment by xcyraxx** [comment]
hi can i work on this?

**Comment by pranshuj73** [comment]
@codePerfectPlus I made a PR, please review it.
