### ISSUE TITLE
Voice input and output

### ISSUE THREAD

**Issue by TechTarun** [Py-Contributors/awesomeScripts#294]
## Script Title - Voice assistant interface

**what will change** -
* Take input in speech and convert into textfile
* Take text file as input and return voice output

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by TechTarun** [comment]
Please assign it to me, I will give a PR today itself.

**Comment by meamedoz** [comment]
Hello, i finished. Should i PR?
