### ISSUE TITLE
Email sending script using smptlib | Python 

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#3]
## Script Title -Email sending script using smptlib

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in the main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by nishit130** [comment]
hey, I would like to work on it

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @nis130 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
HappyCoding,

**Comment by krish-bhanushali** [comment]
Hey, I would love to contribute!

**Comment by codeperfectplus** [comment]
@krish-bhanushali ,
The issue is already assigned, Keep an eye out for upcoming issues.
