### ISSUE TITLE
amazon-price-alert doesn't validate URL

### ISSUE THREAD

**Issue by habereet** [Py-Contributors/awesomeScripts#309]
**Describe the bug**
When requesting the URL from the user, a user can enter a string that isn't a URL without receiving an error. This shouldn't happen

**To Reproduce**
1. Install the required libraries
2. Run the script - python amazon_scraper.py
3. Enter anything for the URL
    - I've tried a blank entry and 'test'
    - Both are accepted but should error
43. See error

**Expected behavior**
When entering an invalid URL, the user should be presented with an error message and be asked to enter their intended URL

**Screenshots**
Blank entry:
![image](https://user-images.githubusercontent.com/41403644/96374179-1a7ddc80-113f-11eb-96bd-f84e8401b1a4.png)

Entry of test:
![image](https://user-images.githubusercontent.com/41403644/96374207-3da88c00-113f-11eb-9200-0db1de066cb6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (on WSL2)
 - Python: 3.8.6

**Comment by codeperfectplus** [comment]
Thanks for pointing out the bug

**Comment by habereet** [comment]
Please assign to me
