### ISSUE TITLE
MorseCode 

### ISSUE THREAD

**Issue by Gourav2000** [Py-Contributors/awesomeScripts#314]
## Script Title -Translates Morse Code to English and vice-versa 

**what will change** -A new folder containing source code for morse code translator will be added.

## Instructions

[x] Create a new folder for your script and file/folder name should be appropriate.
[x] Create a README.md in your folder for program Instructions
[x] add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by Gourav2000** [comment]
I have worked on this before and my PR is ready if it's available assign it to me
