### ISSUE TITLE
Extract any ZIP file into a directory

### ISSUE THREAD

**Issue by dntandan** [Py-Contributors/awesomeScripts#323]
## Script Title - Extract any ZIP file into a directory

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by FredDsR** [comment]
I want solve this. Do you can assign to me?

**Comment by mahesh-kumaran** [comment]
Hey ! Looking for good first issue getting assigned since the start of the month ! Can you please assign this to me. ?

**Comment by dntandan** [comment]
@FredDsR @mahesht10 I already have solved this issue. Just waiting for the maintainer to assign this issue to me so that I can push the changes and make PR. If you guys are interested in solving some other issues then I might create some for you guys. Meanwhile lookup for general & simple issues that are useful to solve.

**Comment by mahesh-kumaran** [comment]
> @FredDsR @mahesht10 I already have solved this issue. Just waiting for the maintainer to assign this issue to me so that I can push the changes and make PR. If you guys are interested in solving some other issues then I might create some for you guys. Meanwhile lookup for general & simple issues that are useful to solve.


Hey @dntandan, Would be glad to contribute ! @codePerfectPlus Can you create a few issues and assign it ?  Been trying a fortnight to make my first contribution !

**Comment by FredDsR** [comment]
> @FredDsR @mahesht10 I already have solved this issue. Just waiting for the maintainer to assign this issue to me so that I can push the changes and make PR. If you guys are interested in solving some other issues then I might create some for you guys. Meanwhile lookup for general & simple issues that are useful to solve.

All issues are already assigned :cry:

**Comment by dntandan** [comment]
> > @FredDsR @mahesht10 I already have solved this issue. Just waiting for the maintainer to assign this issue to me so that I can push the changes and make PR. If you guys are interested in solving some other issues then I might create some for you guys. Meanwhile lookup for general & simple issues that are useful to solve.
> 
> All issues are already assigned :cry: 
@FredDsR You can open any number of issues you want. Just follow the contributions guidelines and it will be assigned to you by @codePerfectPlus

**Comment by codeperfectplus** [comment]
@mahesht10 @FredDsR Please check the new opened issue.

**Comment by FredDsR** [comment]
> @mahesht10 @FredDsR Please check the new opened issue.

Thank you!
