### ISSUE TITLE
Python script to watermark your images

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#332]
## Script Title -Python script to watermark your images

**what will change** - create a new folder, add your script, requirements.txt and README.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by dntandan** [comment]
@codePerfectPlus assign this issue to me.

**Comment by iamneelpatel** [comment]
Hi @codePerfectPlus  can you assign a issue to multiple people, if yes can u assign this to me pls?

**Comment by codeperfectplus** [comment]
@m4dummies It's a simple script for the watermark the image assigning to multiple people doesn't make sense but you can improve the functionality after the pull request.
create an issue for improvement/bug then you can improve it.
