### ISSUE TITLE
social website Blocker using Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#333]
## Script Title - social website Blocker using Python

**what will change** - Social website Blocker using Python during work/study hours.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MaheshBharadwaj** [comment]
I would like to work on this :D

**Comment by Mr-Mishraji** [comment]
hey done website blocker merge pr #354

**Comment by MaheshBharadwaj** [comment]
i thought we had to be assigned to make PR

**Comment by Mr-Mishraji** [comment]
@MaheshBharadwaj but I made it before so I just uploaded it if you want you can add feature. I was not
knowing that.

**Comment by codeperfectplus** [comment]
@MaheshBharadwaj Issue is still open to grab, do you like to be assigned?

**Comment by MaheshBharadwaj** [comment]
No, thanks : D
