### ISSUE TITLE
html2markdown

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#334]
## Script Title - html2markdown vice versa

**what will change** - 

```sh
python html2md -m <file_path>  # chnage in markdown
python html2md -h <file_path>  # chnage in html
```

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by safeers** [comment]
@codePerfectPlus Can you assign this issue to me? I would like to work on it.
