### ISSUE TITLE
csv2json convertor 

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#335]
## Script Title - csv2json and vice versa

**what will change** -
```sh
python csv2json -j <file_path> # convert csv to json
python csv2json -c <file_path> # convert json to csv
```

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sawyer1997** [comment]
@codePerfectPlus Can I try this one?

**Comment by tirthankarkundu17** [comment]
@codePerfectPlus can I work on this ?

**Comment by scienceLabwork** [comment]
Greetings!
I have requested a PR for CSV to JSON converter script.
