### ISSUE TITLE
chage mac address

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#337]
## Script Title - change mac address using python

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by iamneelpatel** [comment]
hi @codePerfectPlus  What os is this script supposed to be for?

**Comment by codeperfectplus** [comment]
It will be good if you can write a script for all OS.

**Comment by iamneelpatel** [comment]
could u assign it to me. Ill make script for mac and windows.

**Comment by iamneelpatel** [comment]
hi @codePerfectPlus i wasnt able to find a efficient way for a script that changes windows mac address. If its ok with you can i make a script for mac os and linux based os?

**Comment by codeperfectplus** [comment]
we are mainly focused on Linux. Go ahead

**Comment by kana800** [comment]
Is this up for grab?

**Comment by codeperfectplus** [comment]
ya @kana800
