### ISSUE TITLE
Get a list of all cuisines of restaurants listed in a city with zomato API

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#338]
## Script Title - Get a list of all cuisines of restaurants listed in a city with zomato API and save in JSON format.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tjrelyts** [comment]
Can I give this a go?

**Comment by sawyer1997** [comment]
Wanted to give a shot, may I?

**Comment by codeperfectplus** [comment]
@sawyer1997 Issue is already assigned, you can find other unassigned issue or can create your own.
