### ISSUE TITLE
YTS Top Movies

### ISSUE THREAD

**Issue by chemsedd** [Py-Contributors/awesomeScripts#358]
## YTS Top Movies

A new script that scraps data from [YTS](https://yts.mx) and shows:

- Most Popular Movies
- Latest Uploads
- Upcoming movies

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shivang8** [comment]
Interested. Please assign it to me.

**Comment by chemsedd** [comment]
I already made the script 😅 just waiting to merge it.
Thanks.
