### ISSUE TITLE
Word Counter

### ISSUE THREAD

**Issue by ghost** [Py-Contributors/awesomeScripts#36]
## Script Title - Word Counter

**what will change** - It will take filename as argument and Calculate frequency of words and rank them :D

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gulvaibhav20** [comment]
@p014ri5 
Hey, I would like to contribute to this issue. Please assign me this issue.
