### ISSUE TITLE
Create Tic Tac Toe game

### ISSUE THREAD

**Issue by jae-yong-2** [Py-Contributors/awesomeScripts#378]
## Script Title - Create Tic Tac Toe game

**what will change** - 
create Tic Tac Toe game.
I would like to work on this issue.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by 96RadhikaJadhav** [comment]
Hey @jae-yong-2 ..Could you please assign this issue to me so I can create a PR.

**Comment by moon4runa** [comment]
Hey can you please assign this issue to me?

**Comment by jae-yong-2** [comment]
Hi, @codePerfectPlus , could i plz be assigned to it?
