### ISSUE TITLE
Duplicated list item in README.md

### ISSUE THREAD

**Issue by AtsushiSakai** [Py-Contributors/awesomeScripts#399]
**Short introduction what you want to change in README.md **
Wrong Readme

I found a duplicated list item in README.md. Should it be fixed?
https://github.com/codePerfectPlus/awesomeScripts/blob/165dd0f95d4a796bfa866e0119480e9344054fb3/README.md#L502-L510

**Comment by codeperfectplus** [comment]
Small Changes Make a Big Difference.

@AtsushiSakai 

Happy Hacktober
