### ISSUE TITLE
scrap_github_repos | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#4]
## Script Title - scrap_github_repos

**what will change** - This script will show all repository and save it in the csv file

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in the main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @codePerfectPlus

**Comment by Jash271** [comment]
Hey I'd love to work on this issue.
