### ISSUE TITLE
Adding a subtitle downloader

### ISSUE THREAD

**Issue by afro-coder** [Py-Contributors/awesomeScripts#401]
## Script Title - Subtitle Downloader

**what will change** - Adds a script to download subtitles from podnapsi

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by afro-coder** [comment]
Please assign this to me

**Comment by codeperfectplus** [comment]
That's a cool script. @afro-coder  

Happy Hacktober

**Comment by afro-coder** [comment]
Thanks, @codePerfectPlus ! 
Happy Hacktober.
