### ISSUE TITLE
Speed Game 

### ISSUE THREAD

**Issue by leecr1215** [Py-Contributors/awesomeScripts#410]
## Script Title - Speed Game 

**what will change** 
[Speed_Game](https://github.com/songyi00/Speed_Game) was made using the Python tkinter module and is a game to guess the name of the country with the national flag image. Anyone can add the category of the game other than guessing the country.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
Interesting and knowledgeable game.

Best of Luck

**Comment by leecr1215** [comment]
@codePerfectPlus  Thanks!!!! 😊
