### ISSUE TITLE
No Download link from Projects links

### ISSUE THREAD

**Issue by shivaabhishek07** [Py-Contributors/awesomeScripts#439]
**There is no link linked to Download link**
In README.md at Projects link section the Download link which specifies that 'Download Specific Scripts from Here ' has no extension link to it

If anyone interested please resolve it or else share the link to me I'll update it

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/107854894/188538536-27ccff8c-3cb9-4cc3-b9c3-265af5b11a45.png)
![Screenshot (3)](https://user-images.githubusercontent.com/107854894/188538547-6643e22a-ab4f-413a-964d-616baf89a892.png)

**Comment by codeperfectplus** [comment]
Sorry for that, but that link is no more working.  Thanks for pointing out the issue. 
@shivaabhishek07
