### ISSUE TITLE
Totp generator in python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#442]
## Script Title - TOTP Generator in python

**what will change** -

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
I would like to take up this issue. Is it still open? If yes please assign it to me.

**Comment by codeperfectplus** [comment]
@ajjayymahato Issue is assigned to you.

Happy Hacktobefest

**Comment by ghost** [comment]
#465
