### ISSUE TITLE
Generate checksum for file in python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#443]
## Script Title - Generate checksum for file in python

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by devbazregari** [comment]
hi bro I hope you're doing great. may I contribute to this project?

**Comment by codeperfectplus** [comment]
Thanks for asking, I am very well. The issue is assigned to you.

Happy HactoberFest
