### ISSUE TITLE
tool that asynchronously scans a server's ports with python.

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#444]
## Script Title - a tool that asynchronously scans a server's ports with python.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
Can you assign this issue to me? It looks interesting.
