### ISSUE TITLE
A script written in Python that logs your input from the keyboard.

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#445]
## Script Title -A script written in Python that logs your input from the keyboard.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gokullan** [comment]
Hi, there! I'm a beginner looking forward to making my first contribution. Could this issue be assigned to me?

**Comment by codeperfectplus** [comment]
@gokullan are you working on the script? Please confirm the status

**Comment by gokullan** [comment]
@codePerfectPlus Yes, I am working on it.
