### ISSUE TITLE
Random Password generator

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#448]
### Argument
1. length of the password
2. only number/number+alpha/number+alpha+specialcase

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by saharsh-solanki** [comment]
Hello Please assign the issue to me

**Comment by saharsh-solanki** [comment]
Hello 
To Whom i should add as assigne 
https://github.com/codePerfectPlus/awesomeScripts/pull/453

**Comment by saharsh-solanki** [comment]
Hello may i know when my PR got merged

**Comment by codeperfectplus** [comment]
PR #453 Merged, Closing the issue now.
