### ISSUE TITLE
IG Script to upload picture on instagram account

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#457]
## Script Title - IG script to upload pictures on Instagram account

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AryanKansagara** [comment]
Can I work on this issue?

**Comment by codeperfectplus** [comment]
This issue is done, and PR is also made.

you can create a new issue for a new script or fix the previous script.

**Comment by AryanKansagara** [comment]
Ok thanks!
