### ISSUE TITLE
New script: get_cpu_process

### ISSUE THREAD

**Issue by TechWiz-3** [Py-Contributors/awesomeScripts#458]
## Get CPU Process

Add a script that allows you to do the following from the terminal:
1. Check if a process is running or not
2. Get PID of a running process
3. Get the runtime of a running process

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
There are already commands for that. for checking process in the terminal, Ex: ` ps -a`

creating a python script will be not that useful in this case.

**Comment by TechWiz-3** [comment]
Oki ty 👍
