### ISSUE TITLE
a simple voice activated alarm/clock app

### ISSUE THREAD

**Issue by avyayjain** [Py-Contributors/awesomeScripts#463]
## Script Title -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
Looks interesting @avyayjain

**Comment by PayalPadmalyaPrusty** [comment]
I want to contribute on this.Please assign me

**Comment by codeperfectplus** [comment]
@PayalPadmalyaPrusty Please create a new issue.
