### ISSUE TITLE
CSV To Excel Convertor - Python Script

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/awesomeScripts#466]
## Script Title - CSV To Excel Convertor - Python Script

**what will change** - New Script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
I want to work on this new script. Can you please assign this to me?

**Comment by codeperfectplus** [comment]
#465
