### ISSUE TITLE
Blackjack Game

### ISSUE THREAD

**Issue by PyroCandy** [Py-Contributors/awesomeScripts#473]
## Script Description -

**A simple Blackjack game which let's the user play against a dealer** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Vaibhav832** [comment]
pls assing it to me..

**Comment by codeperfectplus** [comment]
@PyroCandy are you working on the script? please confirm the status.

**Comment by PyroCandy** [comment]
Nope will not be working on it. Thanks
