### ISSUE TITLE
List Comprehension

### ISSUE THREAD

**Issue by Architgupta001** [Py-Contributors/awesomeScripts#481]
## Script Description -

List comprehension - 
I hade made an explanation to this script of python.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
you can create some scripts that use list comprehension, but only to show list comprehension. it will not be that much helpful.
if you don't have a new script idea. you can improve the existing script or you can write the test cases.
