### ISSUE TITLE
Simple Pomodoro Timer

### ISSUE THREAD

**Issue by dyannya** [Py-Contributors/awesomeScripts#484]
## Script Description -

A GUI pomodoro timer that enables a user to focus on certain tasks for a certain amount of time.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vishaaal** [comment]
I would be glad to be assigned to this

**Comment by dyannya** [comment]
> I would be glad to be assigned to this

Hello! Sorry, I'm currently working on this, hence the post, and was going to ask to be assigned to this issue as well. My apologies I forgot to mention it.

**Comment by codeperfectplus** [comment]
@vishaaal ,

there is more way to create PR/Issue. you can choose.

1. new PR for New Script Idea.
2. improve the existing script.
3. improve documentation
4. write test cases.

**Comment by codeperfectplus** [comment]
PR merged #526
