### ISSUE TITLE
Attachment Downloader

### ISSUE THREAD

**Issue by Somanyu** [Py-Contributors/awesomeScripts#487]
## Attachment Downloader -

**An automation script to download attachments from any mail service (Gmail, Yahoo, etc) using imaplib library. It has various constraints that allows us to download specific files on the basis of extensions or file names or sender.** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
looks interesting
