### ISSUE TITLE
Amazon_Price_Tracker

### ISSUE THREAD

**Issue by SahilSatyam** [Py-Contributors/awesomeScripts#488]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@SahilSatyam , the Same script is already in the repo. Please can you check that? if you want to improve upon that you can make a PR.
