### ISSUE TITLE
Pancake Sorting Algorithm

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/awesomeScripts#499]
## Script Description -
Unlike a traditional sorting algorithm, which attempts to sort with the fewest comparisons possible, the goal is to sort the sequence in as few reversals as possible.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
Please assign this issue to me. I would like to work on this issue.

**Comment by ghost** [comment]
Please check the PR after assigning me this issue #500

**Comment by ghost** [comment]
Also please add the hacktoberfest-accepted label on this PR

**Comment by codeperfectplus** [comment]
we are adding some scripts which solve or automate some tasks, like some bot or something. 
you can add this algorithm in [AlgorithmsAndDataStructure](https://github.com/codePerfectPlus/AlgorithmsAndDataStructure) Repo.
