### ISSUE TITLE
Convert Html to pdf | Python CLI

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#5]
## Script Title - convert `HTML` to `PDF` by taking input from CLI

```bash
python html2pdf.py <website_name>
```
Details: https://www.geeksforgeeks.org/python-convert-html-pdf/

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in main readme

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by hpnightowl** [comment]
can i take this issue?

**Comment by codeperfectplus** [comment]
- [x] assigning the issue to @hpnightowl 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Bhavik-Ardeshna** [comment]
Can i take this plz

**Comment by codeperfectplus** [comment]
@Bhavik-Ardeshna Issue already assigned, wait for new issues or create your new issue for script

**Comment by hpnightowl** [comment]
can you label it as ‘hacktoberfest-accepted’ as per new rules thanks :)
