### ISSUE TITLE
Get Song Lyrics

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/awesomeScripts#501]
## Script Description -
Get Song Lyrics Python Script
**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
Please assign this issue to me and add hacktoberfest-accepted to it as well.

**Comment by ghost** [comment]
Please review this PR and add hacktoberfest-accepted label too #502
