### ISSUE TITLE
Student School Grading System 

### ISSUE THREAD

**Issue by AdityaMathur25** [Py-Contributors/awesomeScripts#506]
## Script Description - this script help user to get its graded in  school also the average marks of student

**what will change** - Make the grading System Online

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@AdityaMathur25 Issue assigned, Interesting project

Happy Hacktoberfest

**Comment by PayalPadmalyaPrusty** [comment]
I am intereseted to contribute.Please assign me

**Comment by codeperfectplus** [comment]
@PayalPadmalyaPrusty This issue is already assigned. you can open a new issue.

Happy Hacktoberfest
