### ISSUE TITLE
A python code for getting the bitcoin price in USD (newbie here)

### ISSUE THREAD

**Issue by Elhasssen** [Py-Contributors/awesomeScripts#508]
## Script Description -

A script that grabs the bitcoin price in USD, the currency can be changed within the code.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@Elhasssen Issue Assigned, Happy Hacktoberfest
