### ISSUE TITLE
CSV to JSON Convertor

### ISSUE THREAD

**Issue by rudrakshi99** [Py-Contributors/awesomeScripts#511]
## Script Description -

Converts CSV file and saves the generated JSON file at the same dir location.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Skvorleksey** [comment]
Hello! I'm interested in working on this issue

**Comment by codeperfectplus** [comment]
Hi, @Skvorleksey Thanks for showing interest in contributing to the project. we are giving first priority to the issue creator. Please create a new issue to add a new script or to fix the previous bug.

**Comment by Skvorleksey** [comment]
Oh, sorry! Ok!
