### ISSUE TITLE
Convert csv to Excel

### ISSUE THREAD

**Issue by ayush-1909** [Py-Contributors/awesomeScripts#519]
## Script Description -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ayush-1909** [comment]
@codePerfectPlus kindly have a look and merge if it fits

**Comment by codeperfectplus** [comment]
@ayush-1909, I have suggested some changes. Please look at the PR and push the code. 
Thanks for contributing.

**Comment by ayush-1909** [comment]
@codePerfectPlus Hey, I'm sorry I'm kinda new to this, I couldn't find your suggestions, can you please help me out?
Thanks.

**Comment by codeperfectplus** [comment]
You will find the changes in the PR. I am mentioning the URL to your PR.

[Your PR](https://github.com/codePerfectPlus/awesomeScripts/pull/520)
