### ISSUE TITLE
A Diff Utility would be awesome!

### ISSUE THREAD

**Issue by KILLinefficiency** [Py-Contributors/awesomeScripts#521]
## Script Description - A Diff Utility compares two files and shows changes accordingly. 

**what will change** - A diff utility script has to be written and added to this repo.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by do159hu** [comment]
Hi, I might be able to do this task. What exactly is the goal? Compare 2 csv files from what aspects? Can you please provide more information?
