### ISSUE TITLE
JSON to YAML

### ISSUE THREAD

**Issue by ayush-1909** [Py-Contributors/awesomeScripts#530]
## Script Description -

A Python Script to convert a file from JSON to YAML

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by do159hu** [comment]
Hi, I can do this issue. Can you assign it to me?
