### ISSUE TITLE
Script to locate addresses

### ISSUE THREAD

**Issue by NishantPacharne** [Py-Contributors/awesomeScripts#537]
## Script Description -
This is a script which will help you to find the latitude and longitude coordinates of any address or even find an address from its coordinates.

Please add/delete options that are not relevant.
- [x] Adding New Code

### Programming Language
- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by RichardSabol** [comment]
Hi, I would like to work on this, could you please assign me the issue?
