### ISSUE TITLE
Water Reminder

### ISSUE THREAD

**Issue by Ayudh-65** [Py-Contributors/awesomeScripts#541]
## Script Description -

It's an application which reminds you to drink water every hour (can be changed) through desktop notifications.
I have the script ready and want to add it.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

Happy Coding

**Comment by Fasicek** [comment]
can I take this issue?
