### ISSUE TITLE
Sound Visualizer

### ISSUE THREAD

**Issue by debdutgoswami** [Py-Contributors/awesomeScripts#55]
## Script Title - sound_visualizer.py

**what will change** -

New script to visualize sound waves on the graph.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by debdutgoswami** [comment]
I would love to add this script

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @debdutgoswami
