### ISSUE TITLE
update Hacktoberfest badge to 2022

### ISSUE THREAD

**Issue by roannav** [Py-Contributors/awesomeScripts#557]
Please assign this issue to me.

**Describe the bug**
The Hacktoberfest badge on the README.md is using the old 2020 badge, so it says "IS OVER! (0 PRS OPENED)"

**To Reproduce**
1. Go to '[github.com/codePerfectPlus/awesomeScripts](https://github.com/codePerfectPlus/awesomeScripts)'
2. Scroll down to the README.md
3. See error at the top part of the README.md, where all the badges are

**Expected behavior**
It should say how many days left for Hacktoberfest (eg "26 DAYS LEFT")

**Screenshots**
None

**Desktop (please complete the following information):**
 - all OS
 - all Browsers

**Smartphone (please complete the following information):**
 - all Devices

**Additional context**
None

**Comment by codeperfectplus** [comment]
@roannav ~I tried to update it But for 2022, It was not working. you can try to change it if it works.~

EDIT: So I have checked that now it's working. you can update the badge.

`https://img.shields.io/github/hacktoberfest/2022/codeperfectplus/awesomescripts`

Happy Hacktoberfest.

**Comment by roannav** [comment]
@codePerfectPlus They came out with a new update 4 days ago, so it'll show the correct number of days left.

If I use https://img.shields.io/github/hacktoberfest/2022/Py-Contributors/awesomescripts?style=for-the-badge
it just says "26 days left"

If I use https://img.shields.io/github/hacktoberfest/2022/codePerfectPlus/awesomescripts?style=for-the-badge
it says "46 PRs, 26 days left"

But isn't 46PRs wrong, since there are only 2 PR open now?  If counting open and closed PRs since Oct 1st, there have been 51 PRs, so I think the 46PR count is a bit off.    Could be that it takes a while to update?

Should I just say the number of days left only?

**Comment by codeperfectplus** [comment]
Agreed, Only add the above one.
