### ISSUE TITLE
File Transfer Protocol Implementation

### ISSUE THREAD

**Issue by Sushant-1999** [Py-Contributors/awesomeScripts#565]
## Script Description -
File Transfer Protocol(FTP) is an application layer protocol that moves files between local and remote file systems. It runs on the top of TCP, like HTTP. To transfer a file, 2 TCP connections are used by FTP in parallel: control connection and data connection. 

**what will change** -
This will add new project which is related to the Computer Networks (Application Layer)

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Sushant-1999** [comment]
@codePerfectPlus please accept the issue so that I can contribute FTP project for this hacktoberfest. Thanks

**Comment by codeperfectplus** [comment]
@Sushant-1999  interesting project. 
Happy hacktoberfest
