### ISSUE TITLE
Added "audiointowavformat.py" in your repo.. 

### ISSUE THREAD

**Issue by vikastripathi707** [Py-Contributors/awesomeScripts#567]
## Script Description -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
# duplicate issue. same PR is merged this week for audio format conversion

**Comment by codeperfectplus** [comment]
Looks like it's a duplicate PR. check #538. if it's an improvement. Please create an issue and you can improve that script
