### ISSUE TITLE
Adding deleting_emails.py

### ISSUE THREAD

**Issue by mansadixit** [Py-Contributors/awesomeScripts#581]
## Deleting emails from a targetted user -

**What will change** - Emails can now be deleted in bulk.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@mansadixit Interesting script. so finally can get rid of some spam emails.

**Comment by mansadixit** [comment]
Yes surely, will be adding the source code.
