### ISSUE TITLE
Pong Game in Python

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/awesomeScripts#593]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
PLease assign this issue to me.

**Comment by ghost** [comment]
#594 Please review this PR
