### ISSUE TITLE
Card Game In Python

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/awesomeScripts#597]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
Please assign this issue to me.

**Comment by ghost** [comment]
Please review this PR #598
