### ISSUE TITLE
sms_sending_script | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#6]
## Script Title - Sms sending to mobile CLI script in python

```bash
python script.py <mobileNO.>
```

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rexdivakar** [comment]
Assign it to me @codePerfectPlus

**Comment by codeperfectplus** [comment]
- [x] Assigning the task to @rexdivakar 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by shivam-S-bisht** [comment]
Just for the curiousness one need to use an external api, and i dont have a one which provide free service☻

**Comment by rexdivakar** [comment]
yes, i have been trying something with free service but SMS needs a paid API, if u wish i can change to a mailing service !! What do u say @shivam-S-bisht

**Comment by shivam-S-bisht** [comment]
Yea, i totally agree. But some services like fast2sms provide a month for free, but this will go temporarily. So you can switch this project to an email service which will be a permanent solution.

**Comment by rexdivakar** [comment]
Let me know the Subject, Body message and recipient mail id so i can work on it

**Comment by shivam-S-bisht** [comment]
Oh yes, you can make an simple api in flask and hit it with the credentials like subject, body and message and recipient email id, which is really scalable and good.
