### ISSUE TITLE
pdf to text

### ISSUE THREAD

**Issue by susritha-s** [Py-Contributors/awesomeScripts#603]
## Script Description -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by jooossshhhh** [comment]
I could work on this. Please assign me and attach an example pdf to change to text. If you do not have an example pdf I can find one to begin working with.

**Comment by jooossshhhh** [comment]
Hello, I just submitted this pull request #608 for the issue.
