### ISSUE TITLE
Script To Generate Passwords

### ISSUE THREAD

**Issue by Akshat-Mishra101** [Py-Contributors/awesomeScripts#606]
## Script Description -

**what will change** -
My idea is to have a script which generates passwords within the range of a given set of parameters. The parameters include the minimum and maximum lengths, occurrence of characters, as well as the valid range for a set of characters.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@Akshat-Mishra101 Same script is already implemented.
https://github.com/Py-Contributors/awesomeScripts/tree/master/Utility_Scripts/random_password_generator

Closing the issue. 
- Duplicate issue 

Thanks
