### ISSUE TITLE
Validator Scripts

### ISSUE THREAD

**Issue by Akshat-Mishra101** [Py-Contributors/awesomeScripts#607]
## Script Description -

Validator Scripts deal with the validation of string based data. Inspired by validator.js, it will support validation of IDs (such as Adhaar, PAN or other international identification numbers) and a few other simpler ones to validate usernames, passwords, phone numbers (with support for country-based locales).

**what will change** -
Addition of a new script library

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add pytest/unittest if possible

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
Looks interesting, can you share an input data string.

**Comment by Akshat-Mishra101** [comment]
We can have validator function for adhaar card called isAdhaar(string). 

According to UIDAI, the adhaar must have 
- It should have 12 digits.
- It should not start with 0 and 1.
- It should not contain any alphabet and special characters.
- It should have white space after every 4 digits.


For instance, if we have the adhaar number "3675 9834 6012", then the function isAdhaar("3675 9834 6012") returns true, as all the conditions are satisfied. If any of the given conditions fail, then the function returns false.

**Comment by codeperfectplus** [comment]
@Akshat-Mishra101 you can check similar project at 
https://github.com/py-contributors/sanatio
