### ISSUE TITLE
Finding broken links

### ISSUE THREAD

**Issue by hruday007** [Py-Contributors/awesomeScripts#65]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by hruday007** [comment]
I have the code ready.

**Comment by htothehilla** [comment]
Hiya, I would like to take this project :)

**Comment by hruday007** [comment]
scripts are added can you review and merge the files.
