### ISSUE TITLE
scrap_all_Links | Python CLI

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#7]
## Script Title - Python CLI tool to scrap link from the input website.

```bash
python script.py <input_website>
```

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in the main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by oxi-git** [comment]
@codePerfectPlus I'd like to work on this!

**Comment by codeperfectplus** [comment]
- [x] Assigning to @Oxigen96 

If You have any idea for a new script then create a new issue for that

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by ghost** [comment]
I have pretty much large knowledge of Selenuim and Bs4 library can youassign me this task for Hackoctober Fest!

**Comment by codeperfectplus** [comment]
@smeet-kothari Welcome to Py-contributors,

The task is already assigned, New issues are coming soon.
If you have any new script idea, please create a new issue.

Happy Coding
