### ISSUE TITLE
remove_punctuation_number | Python CLI

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/awesomeScripts#8]
## Script Title - Python CLI tool to Remove punctuation and Number from the text file. Use Argparser or Click module

```bash
python script.py -n <file_name>    #remove number
python script.py -p <file_name>    #remove punctuation
python script.py -np <file_name>    #remove number and punctuation
```
Hint - Argparser/Click, Regex module

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in the main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rexdivakar** [comment]
Assign it to me

**Comment by codeperfectplus** [comment]
- [x] Assigning to @rexdivakar 

Make sure to take input from CLI as the above example. If you have any script idea then create an issue for that.

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by LowzG** [comment]
Hi I noticed that this got unassigned. If nobody is working on it please feel free to assign it to me.

**Comment by sonniki** [comment]
Looks like this is still not done (the [directory](https://github.com/codePerfectPlus/awesomeScripts/tree/master/remove_punctuation_number) for it is empty). I'll gladly take it! Please assign it to me.

**Comment by sonniki** [comment]
@codePerfectPlus would you mind assigning this one to me? I have a solution ready to go :)
