### ISSUE TITLE
Finding Text Similarity 

### ISSUE THREAD

**Issue by ronika-das** [Py-Contributors/awesomeScripts#86]
## Script Title -

**what will change** -  To find text similarity between two sentences using Cosine Similarity

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ronika-das** [comment]
Can I work on this issue? Please assign it to me

**Comment by sarthak55k** [comment]
Can you assign this to me i have done a lot of work with NLP

**Comment by codeperfectplus** [comment]
@ronika-das Issue assigned.
