### ISSUE TITLE
Create Hangman game

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/awesomeScripts#90]
I would like to work on this issue.

## Script Title - Create Hangman game in Python

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Bug Fix

### Programming Language

- [✓] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
I would like to work on this issue

**Comment by dishak331** [comment]
Hi! I would like to work on this

**Comment by jae-yong-2** [comment]
Hi! I would like to work on this issue

**Comment by jae-yong-2** [comment]
I want to add more kinds of words.

**Comment by jae-yong-2** [comment]
I want to add more kinds of words and some function
