### ISSUE TITLE
Extract mp3 from mp4

### ISSUE THREAD

**Issue by Shanu1515** [Py-Contributors/awesomeScripts#94]
## Script Title -Extracting mp3 from mp4 using Python

**what will change** -You can extract audio(mp3) from a video(mp4) file using Python in 5 lines of code. Your need to have the source-code in the same location of the video file, the program will generate a new mp3 file in that location

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Shanu1515** [comment]
Can you assign this issue to me?
Thank you

**Comment by yashqwerty1** [comment]
I want to work on this Can you assign this to me ?

**Comment by codeperfectplus** [comment]
Use flake8 for code linting
